// Automatically generated by cegarmc
//
#include <assert.h>

int flag;
int i;
int n;
int p;

void main () {
    p = 0;
    n = __VERIFIER_nondet_int();
    __VERIFIER_assume(n >= 100);
    __VERIFIER_assume(n <= 1000);
    flag = __VERIFIER_nondet_int();
    i = 0;
    while (1) {
      if (i < n) {
      } else {
	break;
      }
      if (flag) {
        p += 16;
      } else {
        p += 32;
      }
    i ++;
    }
  
  if (p < 1600 || p > 32000) {
    error();
  }
}
