// Automatically generated by cegarmc
//

extern void __VERIFIER_assume(int);
extern int __VERIFIER_nondet_bool();
extern char __VERIFIER_nondet_char();
extern signed char __VERIFIER_nondet_schar();
extern unsigned char __VERIFIER_nondet_uchar();
extern int __VERIFIER_nondet_int();
extern unsigned int __VERIFIER_nondet_uint();
extern short __VERIFIER_nondet_short();
extern unsigned short __VERIFIER_nondet_ushort();
extern long __VERIFIER_nondet_long();
extern unsigned long __VERIFIER_nondet_ulong();
extern long long __VERIFIER_nondet_longlong();
extern unsigned long long __VERIFIER_nondet_ull();
extern float __VERIFIER_nondet_float();
extern double __VERIFIER_nondet_double();
extern long double __VERIFIER_nondet_longdouble();
extern void * __VERIFIER_nondet_pointer();
int modFlag;
int res;
void error();
void error() {
  {
  goto ERROR;
  ERROR: ;
  return;
  }
}
int main() {
modFlag = __VERIFIER_nondet_int();
res = __VERIFIER_nondet_int();

{
  int n1 = 3;
  int n2 = 5;
  int n3 = 7;
  res = 0;
  auto int bound;
  bound = __VERIFIER_nondet_int();
  {
    int i = 0;
    while (1) {
      if (i < bound) {
        }
      else {
        break;
        }
      {
        if (i % n1 == 0) {
          if (i % n2 == 0) {
            if (i % n3 == 0) {
              res = i;
              }
            else {
              }
            }
          else {
            }
          }
        else {
          }
        }
      i ++;
      }
    }
    modFlag = res;

    __VERIFIER_assume(modFlag % 105 == 0);

    
    if (modFlag % 105 == 0) {

    } else {
      error();
    }
    
    return 0;
 }}
